export enum AppDependencies {
  SPOTIFY_AUTH_PROVIDER = 'SPOTIFY_AUTH_PROVIDER',
  SPOTIFY_AUTH_SERVICE = 'SPOTIFY_AUTH_SERVICE',
  SPOTIFY_AUTH_REPOSITORY = 'SPOTIFY_AUTH_REPOSITORY',
  CACHE_SERVICE = 'CACHE_SERVICE'
}
