export enum AppDependencies {
  LINKING_SERVICE = 'LINKING_SERVICE',
  SPOTIFY_AUTH_PROVIDER = 'SPOTIFY_AUTH_PROVIDER',
  SPOTIFY_OAUTH_SERVICE = 'SPOTIFY_OAUTH_SERVICE',
  SPOTIFY_AUTH_REPOSITORY = 'SPOTIFY_AUTH_REPOSITORY'
}
