export enum AppDependencies {
  SPOTIFY_AUTH_PROVIDER = 'SPOTIFY_AUTH_PROVIDER',
  SPOTIFY_AUTH_SERVICE = 'SPOTIFY_AUTH_SERVICE',
  SPOTIFY_AUTH_REPOSITORY = 'SPOTIFY_AUTH_REPOSITORY',
  CACHE_SERVICE = 'CACHE_SERVICE',
  USER_CACHE_SERVICE = 'USER_CACHE_SERVICE',
  CURRENT_USER_REPOSITORY = 'CURRENT_USER_REPOSITORY',
  FEATURED_PLAYLISTS_REPOSITORY = 'FEATURED_PLAYLISTS_REPOSITORY',
  FEATURED_PLAYLIST_API  = 'FEATURED_PLAYLIST_API',
  API_CLIENT_BUILDER = 'API_CLIENT_BUILDER',
  USER_PROFILE_API = 'USER_PROFILE_API'
}
